server:
  port: 9000
spring:
  application:
    name: operations
  datasource:
    url: jdbc:mysql://operationsdb:3306/operationsdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  sql:
    init:
      mode: always