apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-deployment
spec:
  replicas: 1  # Initial number of pods
  selector:
    matchLabels:
      app: accounts-deployment
  template:
    metadata:
      labels:
        app: accounts-deployment
    spec:
      containers:
        - name: accounts-image
          image: accounts:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
