services:
  accounts:
    image: accounts:latest
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank-microservice
    depends_on:
      - accountsdb

  accountsdb:
    image: mysql:latest
    container_name: accountsdb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=accountsdb
    networks:
      - bank-microservice

  cards:
    image: cards:latest
    container_name: cards-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank-microservice
    depends_on:
      - cardsdb

  cardsdb:
    image: mysql:latest
    container_name: cardsdb
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cardsdb
    networks:
      - bank-microservice

  operations:
    image: operations:latest
    container_name: operations-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank-microservice
    depends_on:
      - operationsdb

  operationsdb:
    image: mysql:latest
    container_name: operationsdb
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: operationsdb
    networks:
      - bank-microservice

networks:
  bank-microservice:
    driver: bridge
