server:
  port: 8080
spring:
  application:
    name: accounts
  datasource:
    url: jdbc:mysql://accountsdb:3306/accountsdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  sql:
    init:
      mode: always