apiVersion: apps/v1
kind: Deployment
metadata:
  name: operations-deployment
spec:
  replicas: 1  # Initial number of pods
  selector:
    matchLabels:
      app: operations-deployment
  template:
    metadata:
      labels:
        app: operations-deployment
    spec:
      containers:
        - name: operations-image
          image: operations:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
