apiVersion: v1
kind: Service
metadata:
  name: cards-service
spec:
  selector:
    app: cards-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: ClusterIP
