apiVersion: v1
kind: Service
metadata:
  name: operations-service
spec:
  selector:
    app: operations-deployment
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
