apiVersion: v1
kind: Service
metadata:
  name: cards-service
spec:
  selector:
    app: cards-deployment
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: ClusterIP
